# WEB PROPERTIES
server:
  port: 8800
  context-path: '/'

# SPRING
spring:
  # DATASOURCE
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://106.15.89.145:5606/dyl-admin?useUnicode=true&characterEncoding=UTF-8'
    username: root
    password: 87166669